api:
  paths:
    tmp_dir: "/tmp/{api_slug}"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "/var/lib/{api_slug}"
    security_dir: "{data_dir}/security"
    ssl_dir: "{data_dir}/security/ssl"
    asymmetric_keys_dir: "{data_dir}/security/asymmetric_keys"
