# services:
#   api:
#     volumes:
#       - "./volumes/.vscode-server:/home/TaskDecomp-user/.vscode-server"
#     deploy:
#       replicas: 3
#       resources:
#         limits:
#           cpus: "0.5"
#           memory: 512M
#     ports: !override
#       - "8000-8002:${TASKDECOMP_API_PORT:-8000}"
#     command: ["/bin/bash"]
#     command: ["-b", "uvicorn api.main:app --host=0.0.0.0 --port=${TASKDECOMP_API_PORT:-8000} --no-access-log --no-server-header --proxy-headers --forwarded-allow-ips='*'"]
#     healthcheck:
#       test: ["CMD-SHELL", "curl -f http://localhost:${TASKDECOMP_API_PORT:-8000}/api/v${TASKDECOMP_API_VERSION:-1}/ping"]
#       start_period: 30s
#       start_interval: 1s
#       interval: 5m
#       timeout: 5s
#       retries: 3
